### ISSUE TITLE
.Net的库没支持.NetStandard的吗。希望之后支持。暂时自己改源码编译standard用了

### ISSUE THREAD

**Issue by liuyl1992** [sensorsdata/sa-sdk-dotnet#1]
.Net的库没支持.NetStandard的吗。希望之后支持。暂时自己改源码用了

**Comment by GvcZhang** [comment]
你好，我们会在你提交的PR上，将.NetStandard支持到1.0。近期会更新版本，非常感谢你的支持。

**Comment by GvcZhang** [comment]
因为无法联系到你，已按照您提交的PR做了一定优化，最新版本：
https://github.com/sensorsdata/sa-sdk-dotnet/releases/tag/v2.0.0
