### ISSUE TITLE
不会实时写入日志bug?

### ISSUE THREAD

**Issue by wtf-boy** [sensorsdata/sa-sdk-dotnet#3]
ConcurrentLoggingConsumer.Flush()内部写入文件流没有调用Flush方法

![image](https://user-images.githubusercontent.com/11848141/84340047-5d003d00-abd2-11ea-9f1c-8aff8f5d82a2.png)
![image](https://user-images.githubusercontent.com/11848141/84340142-93d65300-abd2-11ea-9e46-d2794150cc35.png)

**Comment by GvcZhang** [comment]
这个问题我们有讨论过，按照正常流程当调用 `sa.shutDown`的时候会将缓存中的数据落盘，从这个角度来说是没有影响的。鉴于贡献者以及我们的客户对此问题的关注，我们将会认真处理一下这个问题，非常感谢您提供的宝贵建议。
@wtf-boy

**Comment by GvcZhang** [comment]
@wtf-boy 版本已修复在 [v2.0.2](https://github.com/sensorsdata/sa-sdk-dotnet/releases/tag/v2.0.2)，可以通过Nuget下载
